---
# tasks file for ansible-podman-setup-host
- name: Make sure podman is installed
  package:
    name: podman
    state: present

- name: Allow unprivileged users to bind privileged ports
  sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '80'
    sysctl_set: yes
    state: present
    reload: yes
  when: podman_unprivileged_can_bind_privileged_ports

- name: Add a podman-related unprivileged user
  ansible.builtin.user:
    name: "{{ podman_unprivileged_user_name }}"
    shell: "/usr/bin/bash"
    comment: The user under which all Podman containers run

- name: Enable linger for the unprivileged user
  command:
    cmd: "loginctl enable-linger {{ podman_unprivileged_user_name }}"
  changed_when: false

- name: Enable the podman.socket
  systemd:
    name: podman.socket
    state: started
    enabled: true
    scope: user
  become: true
  become_user: "{{ podman_unprivileged_user_name }}"
